"""Port interfaces (ports & adapters pattern).

These are the stable abstractions the core depends on. Adapters (platform-
specific implementations) live in ``adapters/`` and implement these ports.
"""

from typing import Protocol

from ..core.events import ActivityEvent
from ..core.states import ActivityState
from ..domain.device import DeviceCapabilities

class ProcessMonitor(Protocol):
    """Port: monitor running processes and foreground application."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def get_running_processes(self) -> list[dict[str, object]]: ...
    async def get_foreground_process(self) -> dict[str, object] | None: ...

class BrowserMonitor(Protocol):
    """Port: monitor browser tabs and navigation."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def get_active_tabs(self) -> list[dict[str, object]]: ...

class NetworkMonitor(Protocol):
    """Port: minimal DNS/network telemetry."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def get_recent_domains(self) -> list[dict[str, object]]: ...

class ActionExecutor(Protocol):
    """Port: execute enforcement actions."""

    async def warn(self, request: dict[str, object]) -> dict[str, object]: ...
    async def redirect(self, request: dict[str, object]) -> dict[str, object]: ...
    async def close_application(self, request: dict[str, object]) -> dict[str, object]: ...
    async def block_domain(self, request: dict[str, object]) -> dict[str, object]: ...
    async def enable_restricted_mode(self, request: dict[str, object]) -> dict[str, object]: ...
    async def disable_restricted_mode(self, request: dict[str, object]) -> dict[str, object]: ...

class DeviceController(Protocol):
    """Port: control device-level features."""

    async def get_capabilities(self) -> DeviceCapabilities: ...
    async def enable_restricted_mode(self) -> bool: ...
    async def disable_restricted_mode(self) -> bool: ...
    async def lock_device(self) -> bool: ...

class EventSink(Protocol):
    """Port: send events to subscribers."""

    def subscribe(self, callback: callable) -> None: ...
    async def emit(self, event: ActivityEvent) -> None: ...

class Clock(Protocol):
    """Port: abstract time for testability."""

    def now(self) -> object: ...  # returns datetime-like